[package]
name = "denon-avr-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.28.1"
telnet = "0.2.1"
tokio = "1.39.1"
toml = "0.8.16"
